In [1]:
import os


In [2]:
os.getcwd()

'C:\\Users\\SUDHARSHAN'

In [2]:
import tensorflow as tf

x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [3]:
import keras

In [4]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 21s 2us/step


In [8]:
#print(x_train)

In [13]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS NOT** using the GPU


In [9]:
import numpy as np

In [11]:
np.array(([1,2,3],[3,4,5]))

array([[1, 2, 3],
       [3, 4, 5]])

In [12]:
tf.constant(np.array(([1,2,3],[3,4,5])))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]])>

In [15]:
x = tf.Variable(2.0)

def f(x):
  y = x**2 + 2*x - 5
  return y

f(x)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [16]:
cs=np.array([-40,-10,0,8,15,22,38], dtype='float')
fh=np.array([-40,14,32,46,59,72,100], dtype='float')


In [17]:
lo=tf.keras.layers.Dense(units=1,input_shape=[1])

C:\Users\SUDHARSHAN\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [19]:
model=tf.keras.Sequential(tf.keras.layers.Dense(units=1,input_shape=[1]))

C:\Users\SUDHARSHAN\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


TypeError: 'Dense' object is not iterable