In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier 


In [13]:
os.chdir('F:\TopMentor_DataScience\Batch 103 Day 40')
df1=pd.read_csv('Social_Network_Ads.csv')
df1.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [14]:
x=df1.iloc[:,2:4].values
x

array([[    42, 121315],
       [    53,  67214],
       [    59, 111005],
       [    39,  53414],
       [    39, 114285],
       [    39, 107458],
       [    20,  85582],
       [    59, 148335],
       [    48,  80579],
       [    42, 114204],
       [    32,  87786],
       [    49, 113544],
       [    55,  88300],
       [    54, 147066],
       [    57, 139622],
       [    41, 134716],
       [    51, 116333],
       [    55,  72567],
       [    44, 123254],
       [    47, 113548],
       [    52,  79343],
       [    20, 106149],
       [    40,  59674],
       [    52,  76333],
       [    28, 118742],
       [    22, 105897],
       [    25, 114815],
       [    38,  85428],
       [    57, 114005],
       [    57, 133402],
       [    43, 106726],
       [    35,  84550],
       [    34,  96296],
       [    32,  68964],
       [    55,  90946],
       [    48,  51787],
       [    22,  53940],
       [    42, 138928],
       [    59, 116474],
       [    23,  97284],


In [15]:
y=df1.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [16]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x=ss.fit_transform(x)
x

array([[ 0.17951354,  0.76103154],
       [ 1.11315372, -1.14804259],
       [ 1.622412  ,  0.39722026],
       [-0.0751156 , -1.63500628],
       [-0.0751156 ,  0.51296235],
       [-0.0751156 ,  0.27205647],
       [-1.68776681, -0.49988685],
       [ 1.622412  ,  1.71449234],
       [ 0.68877182, -0.67642883],
       [ 0.17951354,  0.51010409],
       [-0.66925025, -0.42211381],
       [ 0.7736482 ,  0.48681452],
       [ 1.28290648, -0.40397617],
       [ 1.1980301 ,  1.66971285],
       [ 1.45265924,  1.40703476],
       [ 0.09463716,  1.23391563],
       [ 0.94340096,  0.58523059],
       [ 1.28290648, -0.95915007],
       [ 0.3492663 ,  0.82945347],
       [ 0.60389544,  0.48695567],
       [ 1.02827734, -0.72004384],
       [-1.68776681,  0.2258655 ],
       [ 0.00976078, -1.41410826],
       [ 1.02827734, -0.82625839],
       [-1.00875577,  0.67023751],
       [-1.51801405,  0.21697311],
       [-1.26338491,  0.53166458],
       [-0.15999198, -0.50532108],
       [ 1.45265924,

In [17]:
x_test, x_train, y_test, y_train=train_test_split(x,y,test_size=0.3)

In [30]:
classifier =DecisionTreeClassifier(criterion = 'entropy')
classifier .fit(x_train, y_train)
y_pred=classifier .predict(x_test)
print(x_test.shape)
y_pred

(280, 2)


array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [27]:
print('Accuracy Score')
print (accuracy_score (y_test,y_pred),'\n')
print(y_pred.shape)
print('Confusion Matrix')
print (confusion_matrix (y_test,y_pred))
print(y_test.shape)

Accuracy Score
0.55 

(280,)
Confusion Matrix
[[127  55]
 [ 71  27]]
(280,)


In [34]:
#ada=AdaBoostClassifier(estimator= classifier, n_estimators=100, learning_rate=0.8)
ada=AdaBoostClassifier(estimator= classifier, n_estimators=50, learning_rate=0.8)
ada.fit(x_train, y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(), learning_rate=0.8)

In [35]:
y_pred_a=ada.predict(x_test)
print(y_pred_a.shape)
print(y_test.shape)

(280,)
(280,)


In [36]:
print('Accuracy Score')
print (accuracy_score (y_test,y_pred_a),'\n')
print('Confusion Matrix')
print (confusion_matrix (y_test,y_pred_a))

Accuracy Score
0.55 

Confusion Matrix
[[130  52]
 [ 74  24]]


In [33]:
classifier_gini =DecisionTreeClassifier(criterion = 'gini')
classifier_gini .fit(x_train, y_train)
y_pred_gini=classifier .predict(x_test)
print(x_test.shape)
y_pred_gini
print('Accuracy Score')
print (accuracy_score (y_test,y_pred_gini),'\n')
print(y_pred.shape)
print('Confusion Matrix')
print (confusion_matrix (y_test,y_pred_gini))
print(y_test.shape)

(280, 2)
Accuracy Score
0.5535714285714286 

(280,)
Confusion Matrix
[[127  55]
 [ 70  28]]
(280,)


In [47]:
from sklearn import datasets
dir(datasets)
data=datasets.load_digits()
data

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 