In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier 


In [2]:
os.chdir('F:\TopMentor_DataScience\Batch 103 Day 40')
df1 = pd.read_csv('Social_Network_Ads.csv')
print (df1)


      User ID  Gender  Age  EstimatedSalary  Purchased
0    11021175    Male   42           121315          0
1    17782313    Male   53            67214          0
2    14603818  Female   59           111005          0
3    18188198  Female   39            53414          0
4    19357305    Male   39           114285          0
..        ...     ...  ...              ...        ...
395  10220446  Female   20           141231          1
396  12387292    Male   50            75848          1
397  10715173  Female   25            82560          1
398  10016842    Male   55           147667          0
399  11699655  Female   54           134972          1

[400 rows x 5 columns]


In [22]:
x= df1.iloc [:,2:4].values
print (x.shape)
y=df1.iloc [:,4].values
print(y.shape)
print(x.shape)

(400, 2)
(400,)
(400, 2)


In [4]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x = sc_x.fit_transform(x)
print (x)


[[ 0.17951354  0.76103154]
 [ 1.11315372 -1.14804259]
 [ 1.622412    0.39722026]
 [-0.0751156  -1.63500628]
 [-0.0751156   0.51296235]
 [-0.0751156   0.27205647]
 [-1.68776681 -0.49988685]
 [ 1.622412    1.71449234]
 [ 0.68877182 -0.67642883]
 [ 0.17951354  0.51010409]
 [-0.66925025 -0.42211381]
 [ 0.7736482   0.48681452]
 [ 1.28290648 -0.40397617]
 [ 1.1980301   1.66971285]
 [ 1.45265924  1.40703476]
 [ 0.09463716  1.23391563]
 [ 0.94340096  0.58523059]
 [ 1.28290648 -0.95915007]
 [ 0.3492663   0.82945347]
 [ 0.60389544  0.48695567]
 [ 1.02827734 -0.72004384]
 [-1.68776681  0.2258655 ]
 [ 0.00976078 -1.41410826]
 [ 1.02827734 -0.82625839]
 [-1.00875577  0.67023751]
 [-1.51801405  0.21697311]
 [-1.26338491  0.53166458]
 [-0.15999198 -0.50532108]
 [ 1.45265924  0.50308193]
 [ 1.45265924  1.18754822]
 [ 0.26438992  0.24622622]
 [-0.41462111 -0.53630326]
 [-0.49949749 -0.12181953]
 [-0.66925025 -1.08628994]
 [ 1.28290648 -0.31060618]
 [ 0.68877182 -1.6924186 ]
 [-1.51801405 -1.6164452 ]
 

In [5]:
#from sklearn.preprocessing import MinMaxScaler
#mm= MinMaxScaler()
#x = mm.fit_transform(x)
#print (x)

In [6]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=.2)


In [7]:
dtc=DecisionTreeClassifier(criterion='entropy')
ada=AdaBoostClassifier(estimator=dtc,n_estimators=10,learning_rate=0.5)
ada.fit(x_train, y_train)
y_pred=ada.predict(x_test)
print (y_pred)

[0 0 0 0 1 1 0 0 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0
 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0
 0 1 0 1 0 1]


In [8]:
from sklearn.metrics  import accuracy_score,confusion_matrix,classification_report



In [9]:
print(accuracy_score(y_test, y_pred))

0.55


In [10]:
print(confusion_matrix(y_test, y_pred))

[[40 18]
 [18  4]]


In [11]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.69      0.69        58
           1       0.18      0.18      0.18        22

    accuracy                           0.55        80
   macro avg       0.44      0.44      0.44        80
weighted avg       0.55      0.55      0.55        80



In [12]:
from sklearn.preprocessing import MinMaxScaler
mm= MinMaxScaler()
x1 = mm.fit_transform(x)
#print (x1)
x1_train, x1_test, y_train, y_test=train_test_split(x1,y,test_size=.2)
dtc=DecisionTreeClassifier(criterion='entropy')
ada=AdaBoostClassifier(estimator=dtc,n_estimators=10,learning_rate=0.5)
ada.fit(x1_train, y_train)
y_pred=ada.predict(x1_test)
print (y_pred)

[0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1
 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1
 0 0 0 1 1 1]


In [13]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.5125
              precision    recall  f1-score   support

           0       0.59      0.70      0.64        50
           1       0.29      0.20      0.24        30

    accuracy                           0.51        80
   macro avg       0.44      0.45      0.44        80
weighted avg       0.48      0.51      0.49        80



In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.59      0.70      0.64        50
           1       0.29      0.20      0.24        30

    accuracy                           0.51        80
   macro avg       0.44      0.45      0.44        80
weighted avg       0.48      0.51      0.49        80



In [15]:
import xgboost as xgb

from sklearn import datasets
iris=datasets.load_iris()
iris
x,y=iris['data'],iris['target']
print(x.shape)
#y=iris['target']
print(y.shape)

x_train,x_test, y_train,y_test = train_test_split(iris.data, iris.target, test_size = .2)

(150, 4)
(150,)


In [16]:
train = xgb.DMatrix (x_train,label =y_train)
test = xgb.DMatrix (x_test,label =y_test)

In [17]:
param = {'max_depth':4, 'eta':0.3, 'objective': 'multi:softmax', 'num_class': 3}
epochs =10

In [18]:
model=xgb.train( param,train,epochs)
model

In [19]:
predictions=model.predict(test)
predictions

array([0., 0., 2., 2., 2., 2., 1., 1., 2., 0., 0., 1., 0., 2., 2., 1., 2.,
       2., 2., 0., 2., 1., 1., 2., 2., 0., 0., 2., 0., 1.], dtype=float32)

In [20]:
print(y_test)

[0 0 2 2 1 2 1 1 2 0 0 1 0 2 2 1 2 2 2 0 2 1 1 2 2 0 0 2 0 1]


In [21]:
accuracy_score(y_test,predictions)

0.9666666666666667