In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
import os


In [3]:
os.chdir('F:\TopMentor_DataScience\Batch 103 Day 39')

In [4]:
df1=pd.read_csv('mtcars_for_manymerge.csv')
df1.head()

Cars   mpg  cyl   disp   hp  drat  Feedback
0           MazdaRX4  21.0    6  160.0  110  3.90         1
1       MazdaRX4_WAG  21.0    6  160.0  110  3.90         0
2         Datsun_710  22.8    4  108.0   93  3.85         1
3     Hornet_4_Drive  21.4    6  258.0  110  3.08         1
4  Hornet_Sportabout  18.7    8  360.0  175  3.15         1

In [12]:
x=df1.iloc[:,1:6].values
print (x)
y=df1.iloc[:,-1].values
y

[[ 21.     6.   160.   110.     3.9 ]
 [ 21.     6.   160.   110.     3.9 ]
 [ 22.8    4.   108.    93.     3.85]
 [ 21.4    6.   258.   110.     3.08]
 [ 18.7    8.   360.   175.     3.15]
 [ 18.1    6.   225.   105.     2.76]
 [ 14.3    8.   360.   245.     3.21]
 [ 24.4    4.   146.7   62.     3.69]
 [ 22.8    4.   140.8   95.     3.92]
 [ 19.2    6.   167.6  123.     3.92]
 [ 17.8    6.   167.6  123.     3.92]
 [ 16.4    8.   275.8  180.     3.07]
 [ 17.3    8.   275.8  180.     3.07]
 [ 15.2    8.   275.8  180.     3.07]
 [ 10.4    8.   472.   205.     2.93]
 [ 10.4    8.   460.   215.     3.  ]
 [ 14.7    8.   440.   230.     3.23]
 [ 32.4    4.    78.7   66.     4.08]
 [ 30.4    4.    75.7   52.     4.93]
 [ 33.9    4.    71.1   65.     4.22]
 [ 21.5    4.   120.1   97.     3.7 ]]


array([1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0],
      dtype=int64)

In [8]:
from sklearn.model_selection import train_test_split


In [24]:
x_train,x_test, y_train, y_test=train_test_split(x,y)

In [25]:
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train, y_train)
y_pred=knn.predict(x_test)
y_pred

array([0, 1, 0, 0, 0, 0], dtype=int64)

In [16]:
y_test


array([1, 0, 0, 1, 1, 0], dtype=int64)

In [26]:
accuracy_score(y_test, y_pred)

0.16666666666666666

In [39]:
for n in range(4,11):
    x_train,x_test, y_train, y_test=train_test_split(x,y)
    knn=KNeighborsClassifier(n_neighbors=n)
    knn.fit(x_train, y_train)
    y_pred=knn.predict(x_test)
    y_pred
    print('kNN count is ', n, 'and accuracy score is ', accuracy_score(y_test, y_pred))

kNN count is  4 and accuracy score is  0.6666666666666666
kNN count is  5 and accuracy score is  0.5
kNN count is  6 and accuracy score is  0.3333333333333333
kNN count is  7 and accuracy score is  0.6666666666666666
kNN count is  8 and accuracy score is  0.3333333333333333
kNN count is  9 and accuracy score is  0.3333333333333333
kNN count is  10 and accuracy score is  0.8333333333333334


In [40]:
from sklearn.model_selection import cross_val_score

In [52]:
knn=KNeighborsClassifier(n_neighbors=5)
cv=cross_val_score(knn,x,y,cv=5)


In [53]:
print(pd.DataFrame(cv))

      0
0  0.40
1  0.75
2  0.50
3  0.75
4  0.50


In [54]:
cv_score=pd.DataFrame(cv)
cv_score.describe()

0
count  5.000000
mean   0.580000
std    0.160468
min    0.400000
25%    0.500000
50%    0.500000
75%    0.750000
max    0.750000

In [48]:
cv_score.std()

0    0.207966
dtype: float64

In [60]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
cv_lr=cross_val_score(lr,x,y,cv=3)
cv_lr_df=pd.DataFrame(cv_lr)
print(cv_lr_df.describe())

              0
count  3.000000
mean   0.571429
std    0.142857
min    0.428571
25%    0.500000
50%    0.571429
75%    0.642857
max    0.714286


In [62]:
df2=pd.read_csv('Social_Network_Ads.csv')
df2

User ID  Gender  Age  EstimatedSalary  Purchased
0    11021175    Male   42           121315          0
1    17782313    Male   53            67214          0
2    14603818  Female   59           111005          0
3    18188198  Female   39            53414          0
4    19357305    Male   39           114285          0
..        ...     ...  ...              ...        ...
395  10220446  Female   20           141231          1
396  12387292    Male   50            75848          1
397  10715173  Female   25            82560          1
398  10016842    Male   55           147667          0
399  11699655  Female   54           134972          1

[400 rows x 5 columns]

In [104]:
x1=df2.iloc[:,2:4].values
y1=df2.iloc[:,4].values
y1.shape

(400,)

In [80]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
x2=mm.fit_transform(x1)
x2

array([[0.55      , 0.71613824],
       [0.825     , 0.17228935],
       [0.975     , 0.61249724],
       [0.475     , 0.03356521],
       [0.475     , 0.64546935],
       [0.475     , 0.57684111],
       [0.        , 0.35693319],
       [0.975     , 0.98775609],
       [0.7       , 0.30664066],
       [0.55      , 0.6446551 ],
       [0.3       , 0.37908884],
       [0.725     , 0.63802047],
       [0.875     , 0.38425582],
       [0.85      , 0.9749995 ],
       [0.925     , 0.90016888],
       [0.525     , 0.85085144],
       [0.775     , 0.66605682],
       [0.875     , 0.22610024],
       [0.6       , 0.73562999],
       [0.675     , 0.63806068],
       [0.8       , 0.29421581],
       [0.        , 0.56368242],
       [0.5       , 0.0964937 ],
       [0.8       , 0.26395786],
       [0.2       , 0.69027323],
       [0.05      , 0.5611492 ],
       [0.125     , 0.65079716],
       [0.45      , 0.35538511],
       [0.925     , 0.64265466],
       [0.925     , 0.83764249],
       [0.

In [73]:
df2.shape


[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [81]:
x1_train, x1_test, y1_train,y1_test=train_test_split(x2,y1)
print(y1_test)


[0 1 1 0 1 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 1 1
 0 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1
 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0]


In [83]:
knn1=KNeighborsClassifier(n_neighbors=5)
knn1.fit(x1_train, y1_train)
y1_pred=knn1.predict(x1_test)
print(y1_pred)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0
 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]


In [84]:
accuracy_score(y1_test, y1_pred)


0.58

In [87]:
for n in range(4,11):
    x1_train, x1_test, y1_train,y1_test=train_test_split(x2,y1)
    knn=KNeighborsClassifier(n_neighbors=n)
    knn.fit(x1_train, y1_train)
    y1_pred=knn.predict(x1_test)
    y1_pred
    print('kNN count is ', n, 'and accuracy score is ', accuracy_score(y1_test, y1_pred))

kNN count is  4 and accuracy score is  0.59
kNN count is  5 and accuracy score is  0.47
kNN count is  6 and accuracy score is  0.62
kNN count is  7 and accuracy score is  0.57
kNN count is  8 and accuracy score is  0.64
kNN count is  9 and accuracy score is  0.59
kNN count is  10 and accuracy score is  0.67


In [ ]:
cv=cross_val_score(

In [91]:
knn=KNeighborsClassifier(n_neighbors=5)
x1_train, x1_test, y1_train,y1_test=train_test_split(x2,y1)
for n in range(4,11):
    print('cross vlaidation count is --->',n)
    cv2=cross_val_score(knn,x2,y1,cv=n)
    cv2_score=pd.DataFrame(cv2)
    print('cv2_score', cv2_score.describe())
        #print('kNN count is ', n, 'and accuracy score is ', accuracy_score(y1_test, y1_pred))

cross vlaidation count is ---> 4
cv2_score              0
count  4.00000
mean   0.52750
std    0.04717
min    0.46000
25%    0.51250
50%    0.54500
75%    0.56000
max    0.56000
cross vlaidation count is ---> 5
cv2_score               0
count  5.000000
mean   0.535000
std    0.055481
min    0.487500
25%    0.500000
50%    0.512500
75%    0.550000
max    0.625000
cross vlaidation count is ---> 6
cv2_score               0
count  6.000000
mean   0.542477
std    0.058875
min    0.447761
25%    0.524367
50%    0.537879
75%    0.584125
max    0.611940
cross vlaidation count is ---> 7
cv2_score               0
count  7.000000
mean   0.547446
std    0.081585
min    0.438596
25%    0.491228
50%    0.568966
75%    0.578947
max    0.684211
cross vlaidation count is ---> 8
cv2_score              0
count  8.00000
mean   0.51500
std    0.05099
min    0.44000
25%    0.48500
50%    0.53000
75%    0.56000
max    0.56000
cross vlaidation count is ---> 9
cv2_score               0
count  9.000000
mean   0

In [92]:
from sklearn.svm import SVC

In [100]:

x1_train, x1_test, y1_train,y1_test=train_test_split(x2,y1)
svc=SVC(kernel='sigmoid',random_state=0)
svc.fit(x1_train, y1_train)
y1_pred_svc=svc.predict(x1_test)
y1_pred
print('and accuracy score is ', accuracy_score(y1_test, y1_pred_svc))

and accuracy score is  0.55


In [105]:
for n in range(4,11):
    print('cross vlaidation count is --->',n)
    cv2_svc=cross_val_score(svc,x2,y1,cv=n)
    cv2_score_svc=pd.DataFrame(cv2_svc)
    print('cv2_score', cv2_score_svc.describe())

cross vlaidation count is ---> 4
cv2_score               0
count  4.000000
mean   0.520000
std    0.048305
min    0.480000
25%    0.495000
50%    0.505000
75%    0.530000
max    0.590000
cross vlaidation count is ---> 5
cv2_score               0
count  5.000000
mean   0.527500
std    0.058229
min    0.437500
25%    0.525000
50%    0.537500
75%    0.537500
max    0.600000
cross vlaidation count is ---> 6
cv2_score               0
count  6.000000
mean   0.530265
std    0.069342
min    0.417910
25%    0.524367
50%    0.533808
75%    0.537313
max    0.636364
cross vlaidation count is ---> 7
cv2_score               0
count  7.000000
mean   0.530334
std    0.074893
min    0.396552
25%    0.500000
50%    0.526316
75%    0.587719
max    0.614035
cross vlaidation count is ---> 8
cv2_score               0
count  8.000000
mean   0.530000
std    0.078558
min    0.360000
25%    0.515000
50%    0.540000
75%    0.585000
max    0.600000
cross vlaidation count is ---> 9
cv2_score               0
count 