In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os


In [14]:
os.chdir('F:\TopMentor_DataScience\Batch 103 Day 38')
df=pd.read_csv('trans_us.csv',index_col=0,thousands=',')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 207 entries, Afghanistan to Zimbabwe
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1990    207 non-null    int64
 1   1991    207 non-null    int64
 2   1992    207 non-null    int64
 3   1993    207 non-null    int64
 4   1994    207 non-null    int64
 5   1995    207 non-null    int64
 6   1996    207 non-null    int64
 7   1997    207 non-null    int64
 8   1998    207 non-null    int64
 9   1999    207 non-null    int64
 10  2000    207 non-null    int64
 11  2001    207 non-null    int64
 12  2002    207 non-null    int64
 13  2003    207 non-null    int64
 14  2004    207 non-null    int64
 15  2005    207 non-null    int64
 16  2006    207 non-null    int64
 17  2007    207 non-null    int64
dtypes: int64(18)
memory usage: 30.7+ KB


In [15]:
df.isna().sum()
df.index.names=['Country']
df.columns.names=['year']
df.head()

year            1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  \
Country                                                                      
Afghanistan      436   429   422   415   407   397   397   387   374   373   
Albania           42    40    41    42    42    43    42    44    43    42   
Algeria           45    44    44    43    43    42    43    44    45    46   
American Samoa    42    14     4    18    17    22     0    25    12     8   
Andorra           39    37    35    33    32    30    28    23    24    22   

year            2000  2001  2002  2003  2004  2005  2006  2007  
Country                                                         
Afghanistan      346   326   304   308   283   267   251   238  
Albania           40    34    32    32    29    29    26    22  
Algeria           48    49    50    51    52    53    55    56  
American Samoa     8     6     5     6     9    11     9     5  
Andorra           20    20    21    18    19    18    17    19

In [16]:
from sklearn.decomposition import PCA
pca=PCA()
#pca

In [17]:
pca.fit(df)

PCA()

In [18]:
df2=pd.DataFrame(pca.transform(df))
df2

0           1           2           3          4          5   \
0     732.215864  203.381494  -91.386254    4.101273   0.874719   0.275762   
1    -613.296510    4.715978    3.723620   -5.497663   1.970405  -1.057776   
2    -569.303713  -36.837051   22.974094   -7.077382  -2.342223   1.695158   
3    -717.082766    5.464696   28.897037  -12.102115  -3.826874   4.185596   
4    -661.802241   11.037736   26.829058   -4.721499  -0.923666   4.200434   
..           ...         ...         ...         ...        ...        ...   
202  -231.395787  123.076993   -3.670796  205.166799   8.359058  50.234187   
203  -585.225414   14.463482   15.554855   -4.235566  -0.240974   0.673923   
204    59.256311  177.536948    2.828307    2.757493  -6.950651 -20.596663   
205  1488.318012  -15.246686 -400.575028  -29.581610  86.940637 -24.344326   
206  1398.785663 -482.430628  129.258661   14.984799 -60.143291 -75.318917   

            6           7          8           9           10         11  \
0    -3.142209  -12.810095 -12.514548    3.084263  -14.719925  -5.839982   
1    -4.334214    1.633313  -1.162976    2.720540   -1.520743  -0.103493   
2     1.561880    5.413996   0.339645    1.198487    0.695673  -0.318449   
3    -1.302431   -5.457357  -5.949502   -4.693130    2.014447   7.743516   
4     0.199829    4.955191  -0.550326    0.346655   -1.690722  -0.718153   
..         ...         ...        ...         ...         ...        ...   
202  61.091100 -111.614055 -81.261006  106.630245  130.337523  69.478881   
203  -2.050134    5.221590  -2.332248    0.850916   -1.691483  -0.661360   
204   5.244978   14.974251  -3.443525    3.644107   -7.199077  -6.901787   
205 -97.174838   38.178982  24.886382  -15.642597   20.348538  14.051985   
206  54.011376   60.234288 -30.439304    2.601305   12.155409  26.400952   

            12         13         14         15        16        17  
0    -5.838940   7.929728  -3.966920   2.497571 -3.920773  0.206654  
1    -0.798261  -0.345024   0.731178   2.700573 -0.712622  0.353582  
2     0.850217   0.278871   0.863830   0.123622  1.349283  0.009020  
3   -12.121444 -23.631555  -0.270984   6.117575  0.929494  6.367063  
4     0.678574   1.141733  -0.883410  -1.386651 -0.485798 -0.634480  
..         ...        ...        ...        ...       ...       ...  
202   3.278603  23.932691 -17.574498 -11.577597 -2.951267 -7.950805  
203   0.503520   1.452266   0.335004  -0.258312  0.215416 -0.889734  
204  -1.619559   2.929226  -3.560201   0.359692 -1.276769 -3.702018  
205  22.052111 -12.563356  -6.183521  -6.813225 -1.015097 -4.649007  
206 -27.826240 -12.511763  25.021906   5.971226  3.009330  0.121387  

[207 rows x 18 columns]

In [19]:
df3=pd.DataFrame(pca.fit_transform(df))
#df3.Dtypes

In [20]:
pca_evr=pd.DataFrame((pca.explained_variance_ratio_))
#pca_df

In [21]:
#pca_ev=pd.DataFrame((pca.explained_variance_))
#pca_ev  # 792660

In [22]:
bank=pd.read_csv('Bank Data Dimension Reduction.csv',index_col=0)
#bank.info()
print(bank.isnull().sum())


Interest    68
Credit       0
Gender      21
Previous     7
Duration    70
Churn        0
dtype: int64


In [23]:
#bank

In [24]:
bank.groupby('Gender').size()  # getting count of gender for max count
bank['Gender']=bank['Gender'].fillna(0)
bank.isna().sum()


Interest    68
Credit       0
Gender       0
Previous     7
Duration    70
Churn        0
dtype: int64

In [25]:
bank.groupby('Duration')
bank['Duration'].fillna(bank['Duration'].median(),inplace=True)
bank.isna().sum()


Interest    68
Credit       0
Gender       0
Previous     7
Duration     0
Churn        0
dtype: int64

In [26]:
bank.groupby('Previous').size()
bank['Previous']=bank['Previous'].fillna(0)
bank.groupby('Previous').size()

Previous
0.0    309
1.0    291
dtype: int64

In [27]:
bank.groupby('Interest').size()
bank['Interest'].fillna(bank['Interest'].mean(),inplace=True)
bank.isna().sum()

Interest    0
Credit      0
Gender      0
Previous    0
Duration    0
Churn       0
dtype: int64

In [28]:
bank.isna().sum()
print(bank.dtypes)

Interest    float64
Credit        int64
Gender      float64
Previous    float64
Duration    float64
Churn        object
dtype: object


In [29]:
#L=[bank.columns.values]
#L

In [30]:
#for i in L:
#    print('column name is', i ,'and unique values are ' , bank[i].unique)

In [31]:
#for i in L:
#    print('column name is', i )

In [32]:
bank['Gender']=bank['Gender'].astype('category')
bank['Previous']=bank['Previous'].astype('category')
bank['Churn']=bank['Churn'].astype('category')

In [33]:
bank['Churn']=bank['Churn'].cat.codes

In [34]:
bank

Interest  Credit Gender Previous  Duration  Churn
Index                                                   
0       17546.0       1    0.0      0.0      48.0      0
1       30085.1       3    1.0      1.0      40.0      1
2       16575.4       0    0.0      1.0      51.0      1
3       20375.4       3    0.0      0.0      23.0      1
4       50576.3       0    0.0      0.0      57.0      0
...         ...     ...    ...      ...       ...    ...
595     47025.0       2    0.0      1.0      43.0      1
596      9672.3       0    0.0      1.0      43.0      1
597     15976.3       0    0.0      1.0      43.0      0
598     14711.8       0    1.0      0.0      29.0      0
599     26671.6       0    1.0      1.0      38.0      1

[600 rows x 6 columns]

In [35]:
x = bank.iloc[:,0:5].values
print (x.shape)
y = bank.iloc[:,5].values
print (y.shape)

(600, 5)
(600,)


In [36]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x)
x=sc.transform(x)
x

array([[-0.83481117, -0.01104933, -0.96398156, -0.97043679,  0.39357468],
       [ 0.20322955,  1.88312118,  1.03736424,  1.03046381, -0.19900953],
       [-0.91516162, -0.95813458, -0.96398156,  1.03046381,  0.61579376],
       ...,
       [-0.9647577 , -0.95813458, -0.96398156,  1.03046381,  0.02320955],
       [-1.06943845, -0.95813458,  1.03736424, -0.97043679, -1.01381282],
       [-0.07935469, -0.95813458,  1.03736424,  1.03046381, -0.34715558]])

In [37]:
pca1=PCA()

pca_1=pca1.fit_transform(x)
pca_x=pd.DataFrame(pca_1)
pca_x

0         1         2         3         4
0   -0.389348 -1.263066  0.561508  0.217232 -0.783283
1    0.258535  2.122143  0.938872  0.534113  0.167161
2    0.008022 -0.424435 -0.082947 -1.681945 -1.053486
3   -1.330230 -0.276444  2.208619  0.862935  0.660123
4    1.864882 -1.788824 -0.570752  0.196370  0.692477
..        ...       ...       ...       ...       ...
595  1.504013  0.377072  1.179921 -0.631916  1.118015
596 -0.791650 -0.348038  0.038977 -1.813712 -1.039632
597 -0.432636 -0.359121 -0.021943 -1.753198 -0.670900
598 -1.813000 -0.205058 -1.207329  0.564423 -0.046633
599 -0.290127  0.958035 -1.267196 -0.749886  0.112675

[600 rows x 5 columns]

In [38]:
print(pca1.explained_variance_ratio_)

[0.33943997 0.20168854 0.20083191 0.18998087 0.06805872]


In [39]:
pca_2=PCA(n_components=2)
pca_x=pca_2.fit_transform(x)
pca_x.shape

(600, 2)

In [40]:
y.shape

(600,)

In [41]:
from sklearn.model_selection import train_test_split
pca_x_train, pca_x_test,y_train, y_test=train_test_split(pca_x,y,test_size=.2)
print(pca_x_test.shape)
print(pca_x_train.shape)
print(y_train.shape)

(120, 2)
(480, 2)
(480,)


In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
lr=LogisticRegression()
lr.fit(pca_x_train,y_train)
y_pred=lr.predict(pca_x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [43]:
y_test

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int8)

In [44]:
accuracy_score(y_test,y_pred)

0.7583333333333333

In [45]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        29
           1       0.76      1.00      0.86        91

    accuracy                           0.76       120
   macro avg       0.38      0.50      0.43       120
weighted avg       0.58      0.76      0.65       120



C:\Users\SUDHARSHAN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\SUDHARSHAN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\SUDHARSHAN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [46]:
confusion_matrix(y_test, y_pred)

array([[ 0, 29],
       [ 0, 91]], dtype=int64)

In [47]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(pca_x_train,y_train)
y_pred_dt=dt.predict(pca_x_test)
y_pred_dt

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0], dtype=int8)

In [48]:
accuracy_score(y_test,y_pred_dt)

0.65

In [49]:
confusion_matrix(y_test, y_pred_dt)

array([[ 9, 20],
       [22, 69]], dtype=int64)

In [50]:
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=42)
print(x_train.shape,y_test.shape)

(480, 5) (120,)


In [51]:
from sklearn.linear_model import LogisticRegression
lr1=LogisticRegression()
lr1.fit(x_train, y_train)
y_pred=lr1.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [52]:
y_test

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1], dtype=int8)

In [53]:
accuracy_score(y_test, y_pred)

0.7666666666666667