In [5]:
import numpy as np
import pandas as pd

In [6]:
d1=np.arange(9)
d2=np.arange(12)

In [6]:
print (d1)
print()
print(d2)

[0 1 2 3 4 5 6 7 8]

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [97]:
ar1=d1.reshape(3,3)
ar2=d2.reshape(2,2,3)

In [77]:
print (ar1)

print(ar2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [79]:
ar2.ndim

3

In [17]:
ar1.size

9

In [18]:
ar2.dtype

dtype('int32')

In [20]:
ar2[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
ar2[1][1]

array([ 9, 10, 11])

In [27]:
ar2[1][1][1]

10

In [28]:
ar1.itemsize

4

In [29]:
ar1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
type(ar1)

numpy.ndarray

In [42]:
ar3=np.array([(10,20,30),(12,20,12)])
print(ar3)

[[10 20 30]
 [12 20 12]]


In [43]:
ar3.dtype

dtype('int32')

In [44]:
ar3.size

6

In [45]:
ar3.shape

(2, 3)

In [53]:
np.array([(1.0,2), (3,4)]).dtype

dtype('float64')

In [81]:
np.array([(1,0,2)]).shape

(1, 3)

In [82]:
np.array([1,0,2]).shape

(3,)

In [87]:
d4=np.linspace(1,50,9)
d4.reshape(3,3)
print (d4)


[ 1.     7.125 13.25  19.375 25.5   31.625 37.75  43.875 50.   ]


In [100]:
ar1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
ar1.T.ravel()

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [103]:
a = np.array([4., 2.])
b = np.array([3., 8.])

In [106]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [113]:
ar1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
ar1*(ar1)

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [121]:
ar2.sum()

66

In [124]:
ar2.ndim

3

In [13]:
data1=[1,2,3,4,5]

In [19]:
#imoprt numpy as np
arr1=np.array(data1)
arr1.ndim

1

In [15]:
arr1.dtype

dtype('float64')

In [17]:
data2=[[1,2,3,4,5],[10,20,30,40,50]]
arr2=np.array(data2)
arr2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [21]:
print(arr2.dtype,"  ",arr2.ndim)

int32    2


In [ ]:
  #     [[ 1,  2,  3,  4,  5],
       
 #       [10, 20, 30, 40, 50]]

In [25]:
print('arr1 shape is',arr1 ,'arr2 shape is ',arr1.shape)
print('arr2 shape is',arr2 ,'arr2 shape is ',arr2.shape)

arr1 shape is [1. 2. 3. 4. 5.] arr2 shape is  (5,)
arr2 shape is [[ 1  2  3  4  5]
 [10 20 30 40 50]] arr2 shape is  (2, 5)
