In [1]:
import numpy as np
import pandas as pd


In [44]:
a1=np.arange(1,11)
print(a1, type(a1))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [45]:
d1=a1.reshape(2,5)
print(d1)
print (d1.itemsize)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
4


In [46]:
print(a1.ndim)
print("a1 is " , a1.size)
print(d1.ndim)
print("d1 is " , d1.size)
print("d1 is " , d1.itemsize)

1
a1 is  10
2
d1 is  10
d1 is  4


In [26]:
d1.size

10

In [61]:
a2=np.array(([1,2,3],[4,5,6]))
print(a2)

[[1 2 3]
 [4 5 6]]


In [62]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


[   0    1    2 ... 9997 9998 9999]


In [67]:
d1+a2

ValueError: operands could not be broadcast together with shapes (2,5) (2,3) 

In [68]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
print (a1[2:])

[ 3  4  5  6  7  8  9 10]


In [96]:
b=slice(10,20,2)

In [79]:
b

slice(10, 20, 2)

In [86]:
c=[3]
print (c)

[3]


In [93]:
test=a1[c]
print (test)

[4]


In [102]:
s=np.delete (d1,1,1)

In [103]:
print (d1)
print(s)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  3  4  5]
 [ 6  8  9 10]]


In [106]:
np.hstack(s)

array([ 1,  3,  4,  5,  6,  8,  9, 10])

In [111]:
d1[1][4]

10

In [114]:
mat1 = np.arange (0,30)
mat2 =np.reshape (mat1,(6,5),'C')


In [115]:
mat2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [116]:
l1=[1,2,3]
l2=[11,22,33]
l3=[21,22,23]

In [120]:
l=np.array([l1,l2,l3])

In [121]:
l

array([[ 1,  2,  3],
       [11, 22, 33],
       [21, 22, 23]])

In [123]:
b=l.transpose()

In [127]:
l@b

array([[  14,  154,  134],
       [ 154, 1694, 1474],
       [ 134, 1474, 1454]])

In [129]:
l**3

array([[    1,     8,    27],
       [ 1331, 10648, 35937],
       [ 9261, 10648, 12167]], dtype=int32)

In [132]:
for i in l.flat:
    print (i)

1
2
3
11
22
33
21
22
23


In [133]:
l.ravel()

array([ 1,  2,  3, 11, 22, 33, 21, 22, 23])